### ISSUE TITLE
(MAC)Page is getting saved twice with the same title in Bookmarks for some pages

### ISSUE THREAD

**Issue by Mohanme13** [bugbash/selenium-kiwix#100]
Search for French Fries and click on Add Book marks multiple times its saving twice in Book mark list.
But again search for  Cestrum and try to add to Book 
![screen shot 2014-09-06 at 11 53 43 am](https://cloud.githubusercontent.com/assets/8675914/4174427/eab9bcae-358e-11e4-802d-0c71ddfea21d.png)
Mark list , it is not saving.

**Comment by kelson42** [comment]
Thank you very much for your bug report.

This fixed now for the next release:
http://download.kiwix.org/bin/0.9/

Regards
Emmanuel
