### ISSUE TITLE
[MAC] Inverted colours does not apply to all the tabs when an multiple tabs are opened 

### ISSUE THREAD

**Issue by Mohanme13** [bugbash/selenium-kiwix#103]
Open Multipler tabs with certain content opened, From menu bar select Display> Inverted Colors 
Check all the pages opened 
![screen shot 2014-09-06 at 12 17 04 pm](https://cloud.githubusercontent.com/assets/8675914/4174471/30ec56b6-3592-11e4-96fc-e0af055fd0bb.png)
![screen shot 2014-09-06 at 12 14 45 pm](https://cloud.githubusercontent.com/assets/8675914/4174476/73ac1dba-3592-11e4-8d09-a233efdc0dd7.png)

**Comment by kelson42** [comment]
Good catch. I confirm. Will try to fix this ASAP.

**Comment by kelson42** [comment]
So, I finaly have fixed that problem:
sourceforge.net/p/kiwix/kiwix/ci/f8228e5e1560a4cb0518bc482a046410f9dad4aa

Thank you again for this valuable bug report.
