### ISSUE TITLE
Licence information at the footer of a few pages on wikipedia for schools have incomplete information.

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#104]
Licence information at the footer of a few pages on wikipedia for schools have incomplete information.

Example: Pages of 'United States' and 'Copyright and Disclaimer'
Re-producible on: 
OS = Windows 7 Ultimate
Version = Kiwix 0.9 rc2
![incompleteinfo](https://cloud.githubusercontent.com/assets/5223163/4174487/0bcf2984-3593-11e4-91e4-f8964f59829b.png)

**Comment by kelson42** [comment]
Yes, this was a bug in zimwriterfs (the software which packages the content in the ZIM file). We have fixed it a few months ago. Unfortunately we still have a few ZIM files impacted by this in the field. They will be replaced step by step, by the releasing of more up2date versions. Thank you very much for this feedback and congratulations for your accurate page reviewing!
