### ISSUE TITLE
[MAC] Page history surfed is getting lost when user selects Browse History and searches for a file in Library

### ISSUE THREAD

**Issue by Mohanme13** [bugbash/selenium-kiwix#106]
Steps:
1. Go to tools>> Random Article ( Select Twice) Make sure that the Back and forward is enabled
2. Go to Browse library and search for any article and Click Enter 
3. User is Navigated to Table of Context but the Back and Forward is not Enabled

**Comment by kelson42** [comment]
With the 0.9 final, it's not possible to search for articles if the user is in the library (buttons and search bar are disabled). The user can only quit the library and then come back to the exact point he left (and back/forward buttons still work).
