### ISSUE TITLE
[MAC] Application crashes when trying to save an image

### ISSUE THREAD

**Issue by Mohanme13** [bugbash/selenium-kiwix#108]
Steps:
1. Tap (Command Y) to select and image 
2.right click on the image and Click oN save Image as 
3.Type the image name in Save image pop up and click onSave Button
App Crashes

**Comment by rgaudin** [comment]
Can't reproduce on my build from `master`. @kelson42 ?

**Comment by kelson42** [comment]
@Rgaudin, do we have a OSX build (of 0.9 final) to provide to @Mohanme13, to let him test again?

**Comment by rgaudin** [comment]
http://download.kiwix.org/bin/nightly/2014-09-08/kiwix-0.9.dmg

**Comment by kelson42** [comment]
@Mohanme13 
Can you please test again with the given version or at least give us the complete path you wanted to save the image in (this is maybe a unicode or special character problem)?

**Comment by Mohanme13** [comment]
Hey kelson,
I will test it today and post my comments.

**Comment by kelson42** [comment]
@Mohanme13 
Any new feedback?

**Comment by kelson42** [comment]
I close the ticket due to the lack of feedback.
@Mohanme13 please reopen it if you are ready to give us the result of your test.
