### ISSUE TITLE
[MAC] Hide Kiwix (Command H) is not working in OS X 10.9.3

### ISSUE THREAD

**Issue by Mohanme13** [bugbash/selenium-kiwix#111]
Steps to reproduce:
1.  Click on Kiwix>> Hide Others 
2. Click on Hide Kiwix (Command H)

**Comment by kelson42** [comment]
Yes, I have created the feature request upstream. We will further track here your request:
https://sourceforge.net/p/kiwix/feature-requests/832/

Thank you very much for your feature request.
