### ISSUE TITLE
[Vernacular] Preferences pop-up comes up with English text after the user chooses Malayalam language

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#114]
Environment:
OS: Win 7 64-bit
Version: Kiwix 0.9

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Launch Kiwix and Change Language to Malayalam

Open preferences . This opens up with English text

**Comment by kelson42** [comment]
UI translations in ml was not complete. This is complete now, you can check with a nightly build:
http://download.kiwix.org/bin/nightly/

So problem fixed.
