### ISSUE TITLE
Fails one of the claims made on the website 'http://sourceforge.net/projects/kiwix/' 

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#115]
Localized in more than 110 languages.

The downloaded version of kiwix 0.9 rc2 has 103 languages. 
![claimslang](https://cloud.githubusercontent.com/assets/5223163/4174741/7699ac78-35a5-11e4-8a26-ed2c7d3e888f.png)

**Comment by kelson42** [comment]
Yes, http://download.kiwix.org/bin/0.9/ is. We will release it ASAP to match the declaration.

**Comment by aarjay** [comment]
Thank you Kelson.
