### ISSUE TITLE
[Android] The zoom in and zoom out button doesn't work when scrolled down

### ISSUE THREAD

**Issue by shraddha-suman18** [bugbash/selenium-kiwix#117]
The zoom in and zoom out button doesn't work as expected when the page is scrolled down.There are two issues here:
1. The button overlaps with the 'Back to top' option
2. Clicking on the zoom in/out doesn't work rather it scrolls to the top of the screen. The reason could be that the scroll to top button is spanned through the width of the screen.
Device: Nexus 4 Android 4.4.4

![screenshot_2014-09-06-14-11-07](https://cloud.githubusercontent.com/assets/2051019/4175347/4c8652fa-35ce-11e4-84b2-c3ec2416c274.png)

**Comment by kelson42** [comment]
Thank you very much for your bug report. This is indeed a problem/bug.
I have transfered your ticket to the officiel Kiwix bug tracker system:
https://sourceforge.net/p/kiwix/bugs/738/
