### ISSUE TITLE
<Suggestion> Update manager for zim files

### ISSUE THREAD

**Issue by samanway-sprinklr** [bugbash/selenium-kiwix#12]
Update option is not there for zim files. Suggestion - We can have an update manager for kiwix for zim files so that users will be notified about any new update coming in when their machine is connected to the internet.

**Comment by rashiq** [comment]
Good idea! It should be possible since the index of the library list contains a publish date. I'm not sure if the desktop apps already have that, but I'll look into integrating this into the Android download manager (which will be released very soon).

**Comment by samanway-sprinklr** [comment]
Thanks a lot Rashiq because that would be very useful for end users.

**Comment by rashiq** [comment]
😃

**Comment by kelson42** [comment]
Being able to automatically update the content (or trigger the user) if an update is available for a specific content is an old request which is tracked upstream here:
https://sourceforge.net/p/kiwix/feature-requests/695/

This is a feature request for Android too, which of course depends of the implementation of an internal content/download manager:
https://sourceforge.net/p/kiwix/feature-requests/784/

Subscribe these tickets if you want to be kept informed about the progress.
