### ISSUE TITLE
[Mac]Text not displayed on home page when language is changed

### ISSUE THREAD

**Issue by shraddha-suman18** [bugbash/selenium-kiwix#120]
Changing language from English to any other language, displays blank home page after restart.
Device:Mac OS X-10.8.5
Steps:
1.Being on home page, select English.
2.Change the language to Hindi.
(Attaching screenshot of home page when English/Hindi  selected)
Actual behavior: It displays blank page.
Expected behavior: It should display the Home page in Hindi or if the translation is not available I think it should at least show the home page in English.

PS- Not sure if the issue is already reported but I didn't find it logged.

![english selected](https://cloud.githubusercontent.com/assets/2051019/4222276/1025c77c-3912-11e4-9747-a0acd319e234.png)
![hindi selected](https://cloud.githubusercontent.com/assets/2051019/4222277/102b0c6e-3912-11e4-8fef-0ff7ebb820d2.png)

**Comment by kelson42** [comment]
Yes, this page should be localised. The bug is now tracked upstream at:
https://sourceforge.net/p/kiwix/bugs/743/

Thank you for your report.
