### ISSUE TITLE
Software not compatible with MAC

### ISSUE THREAD

**Issue by samanway-sprinklr** [bugbash/selenium-kiwix#14]
Software is not compatible as per the OS features e.g. with mac, the rich user interface it provides is not compatible with the kiwix software which are supported by all other softwares for mac. e.g. navigating back and forth the page, entering and exiting fullscreen mode which might leave the user flummoxed.

**Comment by kelson42** [comment]
Can you please precise how it is and how it should be to your experience for the following feature?
- back and forth the page
- entering and exiting fullscreen mode

**Comment by samanway-sprinklr** [comment]
Yes, I'll explain. In MAC if we swipe left or right with 2 fingers it take
to the previous or the next page.

Also, when we enter the fullscreen mode in the software and if we position
our cursor at the top, the MAC topmost tab should be visible. There will be
a blue icon on the tab which upon clicking has the software exit from
fullscreen mode.

Both of these compatibilities are observed with most of the softwares
designed for mac osx. Hence, to sustain the user friendliness, which is the
USP of mac, in our kiwix as well I thought of making a note of them.

Pardon me if they are beyond the scope of our testing.

**Comment by kelson42** [comment]
The back/left behaviour feature request is tracked upstream:
https://sourceforge.net/p/kiwix/feature-requests/119/

**Comment by rgaudin** [comment]
As for fullscreen, described behavior is the one for the newest versions of OSX (10.8, 10.9).
I agree that should be the way we handle fullscreen in kiwix but that requires some code to match with how FF does this.
We should also support the now common Shift + Apple + F to go to FS.

**Comment by kelson42** [comment]
I have include OSX fullscreen requirements to a new ticket upstream:
https://sourceforge.net/p/kiwix/feature-requests/836/

@samanway-sprinklr Thank you very much for your feedback. All your remarks are now tracked upstream and hopefully will be fixed in next Kiwix release. Fell free to follow these tickets to be keep informed.
