### ISSUE TITLE
Showstopper: Kiwix fails to load after throwing XML parsing error.

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#18]
OS – Windows 8.1
Version - kiwix-0.9-rc2-win
Language - English

Showstopper: Kiwix fails to load after throwing XML parsing error, upon selecting translate language to Kannada from the file menu.

Error message:
XML Parsing Error: error in processing external entity reference
Location: chrome://main/content/main.xul
Line Number 9, Column 1:%mainDTD;
^

**Comment by kelson42** [comment]
Thank you for your bug report. We have fixed this in the 0.9 version like you can see in the CHANGELOG:
https://sourceforge.net/p/kiwix/kiwix/ci/master/tree/CHANGELOG

The oncoming 0.9 version is available here:
http://download.kiwix.org/bin/0.9/
