### ISSUE TITLE
Duplicate entries for  ZIM files are appearing after loading a downloaded ZIM file

### ISSUE THREAD

**Issue by ghost** [bugbash/selenium-kiwix#2]
1.Open Kiwix installed from installer
2.Click Get Files in left nav
3.Download a ZIM file from the list of files displayed and note down its Name 
4.Click My library in left nav
5.Click Load button for the downloaded ZIM file
6.Hover Mouse over File again and click My library
7.Notice the ZIM file downloaded in step 3 appears 2 times here

Expected - Only one entry should be displayed for 1 ZIM file in My library

![duplicate_enteries_for_same_zim_file](https://cloud.githubusercontent.com/assets/8665614/4161791/5f20127c-34d2-11e4-854c-f26078e4e4cb.jpg)

**Comment by kelson42** [comment]
Thank you for your bug report, this was already treated here:
https://github.com/Bug-Bash/selenium-kiwix/issues/4

Kind regards
Emmanuel
