### ISSUE TITLE
Wiktionary: Audio files available on this page do not play. 

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#3]
OS – Windows 8.1
Version - kiwix-0.9-rc2-win
Language - English

Load Wiktionary and search for any search keyword, for example: software.
Audio files available for this search result, does not play.

**Comment by kelson42** [comment]
Yes, I confirm the bug, this is linked to a bad handling of multimedia files in Parsoid. Nothing we at Kiwix can doe for now to fix this. Will post later more detailed informations.

**Comment by aarjay** [comment]
Thank you.

**Comment by kelson42** [comment]
The upstream bug is the following one:
https://bugzilla.wikimedia.org/show_bug.cgi?id=62270

Follow this bug for further information about the fix of this bug. Thank you again for your feedback about this.
