### ISSUE TITLE
Search suggestion contains duplicates

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#32]
Steps to reproduce:
1. Open the zim file - wikipedia_en_ray_charles_03_2013.zim in Kiwix 0.9
2. Confirm generation of Index
3. In the Search box, Start typing 'Sou' 

The  following options starting with 'Soul' get displayed
Soul Brothers
Soul Meeting
Soul Brothers
Soul Meeting
Containing Sou

Actual output:
Soul Brothers
Soul Meeting
Soul Brothers
Soul Meeting
The above is repeated twice which is duplication of suggestion

Expected:
Soul Brothers
Soul Meeting

The search suggestion should contain unique entries.

**Comment by rashiq** [comment]
This is weird. On Android I'm getting the expected output
![screenshot_2014-09-05-14-02-42](https://cloud.githubusercontent.com/assets/1624385/4164458/e52166b0-34f4-11e4-8757-45069e3ba16b.png)

This shouldn't be different across the platforms since the search is backed by the same zim library. @kelson42 can you take a look at that please?

**Comment by kelson42** [comment]
@vinithrasp What is the version you are testing with?

This seems to have been fixed in 0.9 final, see the Changelog:
http://sourceforge.net/p/kiwix/kiwix/ci/master/tree/CHANGELOG

**Comment by vinithrasp** [comment]
@kelson42, @Rashiq ,

I am still able to reproduce this issue on version 0.9.
The search text should be 'Sou' case sensitive to reproduce the issue. I see that you have tried 'sou' as the search text.

**Comment by rashiq** [comment]
@vinithrasp just tried "Sou" as well (and I'm getting the expected output), maybe it's because the Android version doesn't have a full index yet (and thus the search works _a bit_ differently).

**Comment by vinithrasp** [comment]
![search_duplicates_bug](https://cloud.githubusercontent.com/assets/8127422/4200759/50f52d9a-3815-11e4-860f-eb962fbe87d6.png)

**Comment by vinithrasp** [comment]
Environment:
OS: Win 7 64-bit

**Comment by kelson42** [comment]
Thx you for your bug report. This is now fixed.
![screenshot from 2014-09-19 21 59 55](https://cloud.githubusercontent.com/assets/1029718/4341290/a3d41a74-4037-11e4-952c-b4af85e9c6ef.png)
