### ISSUE TITLE
Resume download icon gets changed when user switches to different tab in the left nav

### ISSUE THREAD

**Issue by ghost** [bugbash/selenium-kiwix#33]
OS - Win 7

Steps - 
1.Open Kiwix installed from installer
 2.Click on File menu and click on Browse library icon
 3.Click on Download button for any library and click pause icon
 4.Now click on 'My Library' tab in the left nav
 5.Click on 'Get new files' tab in the left nav

![after_clicking](https://cloud.githubusercontent.com/assets/8665614/4163016/01912f82-34e2-11e4-8820-f8ac85dbde1d.png)

**Comment by kelson42** [comment]
I can confirm that we _had_ indeed a problem here ;)
But now this is fixed (you can check in the futur nightly build).
http://sourceforge.net/p/kiwix/kiwix/ci/5293b1289061934beb2250f6cbfb4eeddc5b198e/
Thank for this useful bug report.
