### ISSUE TITLE
Table of Contents page could be removed from Ctrl+R Random Article

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#36]
Environment:
OS: Win 7 64-bit

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Download the zim file - wikipedia_as_all_07_2013.zim
3. Launch Kiwix and open the above file downloaded in Step 2-wikipedia_as_all_07_2013.zim
4. Press Ctrl+R multiple times to open up Random Article

Actual behavior:
Table of Contents also comes up randomly

Desired behavior:
Ctrl+R should ideally bring up an article and hence Table of contents could be excluded from this list that comes up by pressing Ctrl+R

**Comment by kelson42** [comment]
Yes!

This is now fixed in the source code:
https://sourceforge.net/p/kiwix/kiwix/ci/cfd50820804a7e9324d2b0ed529fa4c8e52b9899/

Thank you very much for this interesting feature request.
