### ISSUE TITLE
Wiktionary - Option to cancel Indexing (which is in progress) is unavailable.

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#5]
OS – Windows 8.1
Version - kiwix-0.9-rc2-win
Language - English

**Comment by kelson42** [comment]
Fully agree with this feature request. I have reported it upstream:
https://sourceforge.net/p/kiwix/feature-requests/831/

Any further activity regarding this feature request will take place on Sourceforge.

Thank you very much for this idea.
