### ISSUE TITLE
[Android] Shared with friends option in the settings Menu in Vernacular shows English Text

### ISSUE THREAD

**Issue by sunitavc** [bugbash/selenium-kiwix#51]
When kiwix is rendered in Tamil/French etc the Options -> Share with friends text is displayed in English.
![language_error](https://cloud.githubusercontent.com/assets/5976280/4164214/ebbeac4c-34f1-11e4-9516-9f3105068af1.png)

**Comment by rashiq** [comment]
Good catch! Didn't notice that it wasn't translated yet, thanks @sunitavc. 
We will update the strings :smiley:

**Comment by sunitavc** [comment]
Thanks @Rashiq the version of Android is 4.4.4

**Comment by kelson42** [comment]
Thank you for your feedback, this string is now translated and will be available in next release:
https://translatewiki.net/w/i.php?title=Kiwix:Android.ui.menu_share/ta

Same for French:
https://translatewiki.net/w/i.php?title=Kiwix:Android.ui.menu_share/fr

But a few strings of the UI still need to be translated in Tamil:
https://translatewiki.net/w/i.php?title=Special:Translate&group=out-kiwix&language=ta&filter=!translated&action=translate

Your help would be really welcome, you just need to register on translatewiki.net to translated the last one.
