### ISSUE TITLE
[Team SCube] [Android] Preferences in Vernacular rendered differently for Hindi and Tamil

### ISSUE THREAD

**Issue by sunitavc** [bugbash/selenium-kiwix#57]
Android 4.4.4
Set language preferences to Tamil, see that the preference settings is mostly rendered in English.
![tamil_preferences](https://cloud.githubusercontent.com/assets/5976280/4164534/58044f98-34f6-11e4-87c5-5d07ebe9b6c0.png)
Set language preferences to Hindi, see that the preference settings is rendered mostly in Hindi (has a couple of them in English)
![hindi_preferences](https://cloud.githubusercontent.com/assets/5976280/4164532/56b63f48-34f6-11e4-9589-1aa54bdbe611.png)

**Comment by rashiq** [comment]
Thanks for bringing that to our attention! 
Apparently we missed the translation of some strings. It's hard to keep track since the app is translated into 87 languages (in Android; the desktop version has even more languages you can chose from).

I'll look into it :smiley:

**Comment by kelson42** [comment]
The Kiwix UI localisation in Tamil needs your help!

A few strings still need to be translated:
https://translatewiki.net/w/i.php?title=Special:Translate&group=out-kiwix&language=ta&filter=!translated&action=translate

Would you be able to do it on translatewiki.net?

**Comment by kelson42** [comment]
Kiwix is localized in more than hundred languages and add time to time new strings to translate. We rely on volunteers to translate the UI and we don't want to remove languages which are still not fully translated (anymore). We would really appreciate your help to translate the Kiwix UI in Tamil. But there is nothing else we can do here. So I close the ticket.
