### ISSUE TITLE
Kiwix – uninstallable unavailable for language English [Kiwix-uninstall.exe]

### ISSUE THREAD

**Issue by aarjay** [bugbash/selenium-kiwix#6]
OS – Windows 8.1
Version - kiwix-0.9-rc2-win
Language - English

This behaviour is observed when more than one version(different languages) of the software is installed on the same machine.

**Comment by kelson42** [comment]
Sorry but I don't understand the problem, may I have please a more detailed description of the problem?

**Comment by aarjay** [comment]
Sorry too, closing this issue as it cannot be re-produced. 
I will provide sufficient information if I encountered this issue on any other device that I use. 
Thank you.
