### ISSUE TITLE
[Team SCube] [Android] Changing Zoom Level on Settings does not change actual font size

### ISSUE THREAD

**Issue by sunitavc** [bugbash/selenium-kiwix#61]
Change the zoom level on Settings to High, Small or Automatic, the text is always rendered in a standard size.

![zoom](https://cloud.githubusercontent.com/assets/5976280/4164629/faacbf90-34f7-11e4-9d85-153774dc6553.png)
![zoom_not_working](https://cloud.githubusercontent.com/assets/5976280/4164630/fcd8acca-34f7-11e4-9bb7-db60d8068db4.png)

**Comment by kelson42** [comment]
Yes, the zoom feature does not work well. The problem(s) are tracked upstream here:
https://sourceforge.net/p/kiwix/bugs/703/
