### ISSUE TITLE
Missing languages in Filter options

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#62]
Environment:
OS: Win 7 64-bit

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Download the zim file - wikipedia_as_all_07_2013.zim and couple of files in other languages
3. Launch Kiwix and open the above files downloaded in Step 2
4. Click on File-> Browse Library
5. In Filter by Language, only the 'All' and 'English' are listed and 'asm' language is missing

PFA screenshot with zim files of 3 languages, yet only 'All' and 'English' listed in Filter options.

Actual Behavior:
In Filter by Language, only the 'All' and 'English' are listed and 'asm' language is missing

Desired Behavior:
The Filter by language should have 'All' 'English' and 'asm' based on the list of languages loaded in the library

**Comment by kelson42** [comment]
Can you please confirm with this dev. version:
http://download.kiwix.org/bin/0.9/

The normal behaviour is that _all languages_ are listed in the "filter by language" select box.

**Comment by vinithrasp** [comment]
![language_missing](https://cloud.githubusercontent.com/assets/8127422/4200701/b2770652-3814-11e4-8082-f62c0542ea04.png)

**Comment by kelson42** [comment]
Thank you very much for your bug report.
Your screenshot comes from the 0.9rc2 I guess.

This is fixed in the kiwix 0.9 final, which will be released soon. See screenshot.
![screenshot from 2014-09-11 22 40 20](https://cloud.githubusercontent.com/assets/1029718/4241551/e1a3d928-39f4-11e4-96b1-19d8c970c677.png)
