### ISSUE TITLE
Navigating through bookmarks and Viewing - Key Board 'Enter' doesn't work

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#64]
Environment:
OS: Win 7 64-bit

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Download the zim file - wikipedia_as_all_07_2013.zim
3. Launch Kiwix and open the above file downloaded in Step 2-wikipedia_as_all_07_2013.zim
4. In table of contents, click on for example the link, Ray Charles
5. In Bookmarks section, Click on + - 'Mark this page' and Bookmark gets added with text Ray Charles
6. Add couple of bookmarks by repeating the Step 5
7. Now, click on one of the Bookmarks, and try navigating through the bookmarks through keyboard 'UP' and 'Down' arrows and Hit 'Enter' to view a page

Actual Behavior:
'Enter' key doesn't bring up the Bookmarked page, only mouse click on the Bookmarked page works.

Desired Behavior:
Keyboard 'Enter' event should be handled to bring up the Bookmarked page

**Comment by kelson42** [comment]
Perfect bug report. This is fixed now:
https://sourceforge.net/p/kiwix/kiwix/ci/54133714d0ca67c64007827b1ba639dfb3307c4b

Thank you
