### ISSUE TITLE
Zim file  wikipedia_th_all_02_2013.zim download link throws 403 - Forbidden in http://download.kiwix.org/zim/0.9/

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#66]
Open http://download.kiwix.org/zim/0.9/

Try to download file -wikipedia_th_all_02_2013.zim

This throws 403-Forbidden error

Error URL- http://dumps.wikimedia.org/kiwix/zim/0.9/wikipedia_th_all_02_2013.zim

PFA the screenshot with the issue.

**Comment by rashiq** [comment]
Hmm this is weird. It returns a 200 http status code for me: 

![](http://cl.ly/image/2k3C1w382u25/Image%202014-09-05%20at%202.55.30%20nachm..png)

I can't imagine this being blocked in another country or anything similar.

**Comment by kelson42** [comment]
It works for me too. Maybe a censorship problem or more probably a temporary problem in the Wikimedia datacenter. I close the bug because this is not reproducable. Thank you anyway for having noticed and reported this.
