### ISSUE TITLE
[Team SCube][Windows][Vernacular] Show Library in Hindi, Hide Library in English

### ISSUE THREAD

**Issue by sunitavc** [bugbash/selenium-kiwix#67]
Show Library is in Hindi
![showlibrary](https://cloud.githubusercontent.com/assets/5976280/4164752/1356554a-34fa-11e4-9bbf-2c50757e04ac.png)

But Hide Library is in English
![hidelibrary](https://cloud.githubusercontent.com/assets/5976280/4164751/11448204-34fa-11e4-9ccc-c7c6073d7258.png)
Windows 7

**Comment by kelson42** [comment]
This is now fixed. Thx for the bug report.
![screenshot from 2014-09-17 06 09 38](https://cloud.githubusercontent.com/assets/1029718/4298372/b7c1b118-3e20-11e4-8874-126b32d9d837.png)
