### ISSUE TITLE
HOT Bug: Typing the char '*' in My Library 'Search zim file' text box crashes Kiwix

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#69]
Environment:
OS: Win 7 64-bit

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Download the zim file - wikipedia_as_all_07_2013.zim
3. Launch Kiwix and open the above file downloaded in Step 2-wikipedia_as_all_07_2013.zim
4. Click on File-> Browse Library
5. Type the char \* in Search zim files text box

Kiwix crashes

**Comment by julianharty** [comment]
Also reproduced in Kiwix for Mac OSX

Process:         xulrunner [70556]
Path:            /Applications/Kiwix.app/Contents/MacOS/xulrunner
Identifier:      org.kiwix.kiwix
Version:         0.9 (1.0)
Code Type:       X86-64 (Native)
Parent Process:  ??? [1]
Responsible:     xulrunner [70556]
User ID:         502

Date/Time:       2014-09-05 14:35:07.580 +0100
OS Version:      Mac OS X 10.9.4 (13E28)
Report Version:  11
Anonymous UUID:  ACFE8104-A8C4-4E05-F521-A6AA29F41F6F

Sleep/Wake UUID: 1CBFA1FF-420A-4EE4-9E0D-074EC4DB53AE

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000000000000b8

VM Regions Near 0xb8:
--> 
    __TEXT                 0000000100000000-0000000100005000 [   20K] r-x/rwx SM=COW  /Applications/Kiwix.app/Contents/MacOS/xulrunner

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libicui18n.dylib                0x0000000109d2e7cc icu_49::RegexMatcher::reset(icu_49::UnicodeString const&) + 44
1   contentManager.dylib            0x000000010c92b32f matchRegex(std::string const&, std::string const&) + 79
2   contentManager.dylib            0x000000010c91fc14 kiwix::Manager::listBooks(kiwix::supportedListMode, kiwix::supportedListSortBy, unsigned int, std::string, std::string, std::string, std::string) + 1044
3   contentManager.dylib            0x000000010c9180a2 ContentManager::ListBooks(nsACString const&, nsACString const&, unsigned int, nsACString const&, nsACString const&, nsACString const&, nsACString const&, bool_) + 594
4   XUL                             0x0000000104220933 NS_InvokeByIndex_P + 739
5   XUL                             0x0000000103d12469 0x10326a000 + 11175017
6   XUL                             0x0000000103d1a94c 0x10326a000 + 11209036
7   XUL                             0x00000001045bb74c 0x10326a000 + 20256588
8   XUL                             0x00000001045acfea 0x10326a000 + 20197354
9   XUL                             0x00000001045bb082 0x10326a000 + 20254850
10  XUL                             0x00000001045bb67c 0x10326a000 + 20256380
11  XUL                             0x00000001045bbccc 0x10326a000 + 20257996
12  XUL                             0x00000001045332b1 JS_CallFunctionValue + 65
13  XUL                             0x00000001039713e3 0x10326a000 + 7369699
14  XUL                             0x00000001039e3e28 0x10326a000 + 7839272
15  XUL                             0x00000001037dc99a 0x10326a000 + 5712282
16  XUL                             0x00000001037fdb5d 0x10326a000 + 5847901
17  XUL                             0x00000001037feb68 0x10326a000 + 5852008
18  XUL                             0x00000001034bbfe4 0x10326a000 + 2432996
19  XUL                             0x00000001034bcec5 0x10326a000 + 2436805
20  XUL                             0x0000000103a768f7 0x10326a000 + 8440055
21  XUL                             0x00000001036b6946 0x10326a000 + 4507974
22  XUL                             0x0000000103a6dec0 0x10326a000 + 8404672
23  XUL                             0x0000000103a6e24a 0x10326a000 + 8405578
24  XUL                             0x0000000103a645a2 0x10326a000 + 8365474
25  XUL                             0x0000000103a615c5 0x10326a000 + 8353221
26  XUL                             0x0000000103a7a568 0x10326a000 + 8455528
27  XUL                             0x0000000103a7ae4d 0x10326a000 + 8457805
28  XUL                             0x00000001037dc99a 0x10326a000 + 5712282
29  XUL                             0x00000001037fdda9 0x10326a000 + 5848489
30  XUL                             0x00000001037fdc7c 0x10326a000 + 5848188
31  XUL                             0x00000001037feb68 0x10326a000 + 5852008
32  XUL                             0x00000001034bbfe4 0x10326a000 + 2432996
33  XUL                             0x00000001034be278 0x10326a000 + 2441848
34  XUL                             0x000000010395dbfa 0x10326a000 + 7289850
35  XUL                             0x000000010395a061 0x10326a000 + 7274593
36  XUL                             0x000000010403e435 0x10326a000 + 14500917
37  XUL                             0x0000000104038882 0x10326a000 + 14477442
38  XUL                             0x000000010405c0ed 0x10326a000 + 14622957
39  XUL                             0x00000001040666e4 0x10326a000 + 14665444
40  XUL                             0x000000010403c012 0x10326a000 + 14491666
41  com.apple.AppKit                0x00007fff8bf756c7 -[NSTextInputContext insertText:replacementRange:] + 379
42  com.apple.AppKit                0x00007fff8bf74978 -[NSTextInputContext handleTSMEvent:] + 8271
43  com.apple.AppKit                0x00007fff8bf72905 _NSTSMEventHandler + 205
44  com.apple.HIToolbox             0x00007fff91b261d4 DispatchEventToHandlers(EventTargetRec_, OpaqueEventRef_, HandlerCallRec_) + 892
45  com.apple.HIToolbox             0x00007fff91b25787 SendEventToEventTargetInternal(OpaqueEventRef_, OpaqueEventTargetRef_, HandlerCallRec*) + 385
46  com.apple.HIToolbox             0x00007fff91b39880 SendEventToEventTarget + 40
47  com.apple.HIToolbox             0x00007fff91b7ad0d SendTSMEvent + 33
48  com.apple.HIToolbox             0x00007fff91b7a89b SendUnicodeTextAEToUnicodeDoc + 473
49  com.apple.HIToolbox             0x00007fff91b7a595 TSMKeyEvent + 546
50  com.apple.HIToolbox             0x00007fff91b672b7 TSMProcessRawKeyEvent + 3807
51  com.apple.AppKit                0x00007fff8bf72150 -[NSTextInputContext handleEvent:] + 731
52  com.apple.AppKit                0x00007fff8bf519dd -[NSView interpretKeyEvents:] + 180
53  XUL                             0x000000010406400c 0x10326a000 + 14655500
54  XUL                             0x000000010403c4a5 0x10326a000 + 14492837
55  com.apple.AppKit                0x00007fff8bf1e56b -[NSWindow sendEvent:] + 1843
56  XUL                             0x0000000104030832 0x10326a000 + 14444594
57  com.apple.AppKit                0x00007fff8bebfb32 -[NSApplication sendEvent:] + 3395
58  XUL                             0x000000010402d328 0x10326a000 + 14431016
59  com.apple.AppKit                0x00007fff8bd0f9f9 -[NSApplication run] + 646
60  XUL                             0x000000010402d79d 0x10326a000 + 14432157
61  XUL                             0x0000000103e947e4 0x10326a000 + 12756964
62  XUL                             0x0000000103271462 0x10326a000 + 29794
63  XUL                             0x00000001032760eb 0x10326a000 + 49387
64  XUL                             0x00000001032765f3 XRE_main + 307
65  org.kiwix.kiwix                 0x0000000100001e8f 0x100000000 + 7823
66  org.kiwix.kiwix                 0x0000000100001bb4 start + 52

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib          0x00007fff915b1662 kevent64 + 10
1   libdispatch.dylib               0x00007fff9056f421 _dispatch_mgr_invoke + 239
2   libdispatch.dylib               0x00007fff9056f136 _dispatch_mgr_thread + 52

Thread 2:: Gecko_IOThread
0   libsystem_kernel.dylib          0x00007fff915b164a kevent + 10
1   XUL                             0x000000010423871e 0x10326a000 + 16574238
2   XUL                             0x0000000104236a09 0x10326a000 + 16566793
3   XUL                             0x000000010424a026 0x10326a000 + 16646182
4   XUL                             0x000000010423f370 0x10326a000 + 16601968
5   XUL                             0x0000000104245273 0x10326a000 + 16626291
6   XUL                             0x000000010424a67a 0x10326a000 + 16647802
7   libsystem_pthread.dylib         0x00007fff8e5f3899 _pthread_body + 138
8   libsystem_pthread.dylib         0x00007fff8e5f372a _pthread_start + 137
9   libsystem_pthread.dylib         0x00007fff8e5f7fc9 thread_start + 13

-- cut --

**Comment by rashiq** [comment]
Oh, good catch! Can reproduce it on my mac as well. 
@rgaudin can you please a look at that?

**Comment by rgaudin** [comment]
doesn't seem osx specific. @kelson42 ?

**Comment by kelson42** [comment]
I can not reproduce the  bug on linux. Will check on windows ASAP.

**Comment by kelson42** [comment]
I was finally able to reproduce the bug and to fix it:
sourceforge.net/p/kiwix/kiwix/ci/bc51f177bb6e5681d1b843f9d90815ffce3ef27d

Thank very much for having helped to fix this really annoying problem.
