### ISSUE TITLE
Unchecking Preferences->Download remote catalog(s) option doesn't work

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#74]
Environment:
OS: Win 7 64-bit

Version: Kiwix 0.9

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Click on Edit-> Preferences
3. Initially by defualt, Download remote catalog(s)  will be unchecked
4. Check this option and click on Ok
5. Kiwix confirms for 'Restart' and the change comes to effect (Get new files' has a list of options to download.
6. Now, traverse the same menu to uncheck the Download remote catalog(s) option.

Actual behavior:
No action taken not restart happens. Get new files still lists the files for download.

Expected behavior:
Uncheck of Download remote catalog(s) option should restart kiwix and change should come to effect

**Comment by kelson42** [comment]
Thank you for your bug report. This option is only about downloading the catalog, that means the list of content available online (not the content themself). Checking/unchecking should not require a restart to apply. If this is unchecked and Kiwix has downloaded a catalog in the past then it will still continue to display it. In the 0.9 version, before doing anything, the user is asked (at the first start) if he want to download the catalog. So, everything is fixed and AFAIK works fine in 0.9 final (to be released soon):
http://download.kiwix.org/bin/0.9/

Regards
Emmanuel
