### ISSUE TITLE
Clicking on bookmarked page of non-existing library file doesn't throw error/appropriate message

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#75]
Environment:
OS: Win 7 64-bit

Version: Kiwix 0.9

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Download the zim file - wikipedia_as_all_07_2013.zim
3. Launch Kiwix and open the above file downloaded in Step 2-wikipedia_as_all_07_2013.zim
4. Bookmark couple of pages from the above zim file
5. Now, go to 'Browse Library' and remove the zim file- 'wikipedia_as_all_07_2013.zim' that shows up in the list without deleting the contents.
6. Now click on the bookmarked page, 

Actual behavior:
it asks for confirmation 'This bookmark is refering to another content. Do you want to load it?'
On clicking yes, results in blank page

Desired behavior:
Shoudl throw appropriate error / message that zim file/content is missing in library.

**Comment by kelson42** [comment]
This is IMO pretty much similar to :
https://github.com/Bug-Bash/selenium-kiwix/issues/73

Now, such steps will generate this behaviour:
- Ask for opening wikipedia_as_all_07_2013.zim
- If file is not in library, will open a dialog box "open file".

So, it's already fixed in 0.9 final :)
