### ISSUE TITLE
'Inverted Colors' in Vernacular (Malayalam) shows up in English

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#77]
Environment:
OS: Win 7 64-bit

Version: Kiwix 0.9

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Launch Kiwix and change language to Malayalam
3. Check View->Inverted Colors which shows up in English

PFA screenshot of the issue.

**Comment by vinithrasp** [comment]
![malayalam_inverted_colors_menu](https://cloud.githubusercontent.com/assets/8127422/4198024/78dc4a4a-37f3-11e4-9f8d-0f880fb9c4f5.png)

**Comment by kelson42** [comment]
Thank for you bug report, it's now fixed in dev version:
![screenshot from 2014-09-12 21 35 41](https://cloud.githubusercontent.com/assets/1029718/4255339/2549cb14-3ab4-11e4-937b-1c0d1cd8355c.png)
