### ISSUE TITLE
Vernacular:Navigating between bookmarked pages in different zim files- confirmation pops up in English

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#79]
Environment:
OS: Win 7 64-bit

Version: Kiwix 0.9

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Launch Kiwix and change language to Tamil
3. Try navigating to bookmarked pages across zim files

Actual behavior:
Confirmation message pops up in English whereas chosen language is Tamil.

PFA screenshot of the issue.

**Comment by vinithrasp** [comment]
![confirmation_lang_issue](https://cloud.githubusercontent.com/assets/8127422/4200649/2e7b93fe-3814-11e4-8ba0-3d58885ae203.png)

**Comment by kelson42** [comment]
Thank you for reporting that bug. We have fixed the code to display a localised version of this message. But of course this string still needs to be translated by volunteer translators. Help us to complete the Kiwix UI localisation in Tamil: https://translatewiki.net/w/i.php?title=Special:Translate&group=out-kiwix&language=ta&filter=!translated&action=translate
