### ISSUE TITLE
[Usability] Filter By results not dynamic as per selection

### ISSUE THREAD

**Issue by vinithrasp** [bugbash/selenium-kiwix#81]
Environment:
OS: Win 7 64-bit

Steps to reproduce:
1. Install Kiwix 0.9- from kiwix-0.9-rc2-installer.exe
2. Download the zim file - wikipedia_as_all_07_2013.zim
3. Click on Browse Library->Get new Files
4. In Filter By -> Language, Select English

Actual Behavior:
Filter By- > Author, Publisher results are not refreshed based on Author selection.
The values in the Author, Publisher drop down includes all values which do not correspond to the Language being selected already.

Desired Behavior:
The values in the Author, Publisher drop down should be refreshed to only available values based on the Language being selected already and vice versa.

**Comment by kelson42** [comment]
Yes, totally agree. The bug will be tracked upstream at this URL:
https://sourceforge.net/p/kiwix/feature-requests/837/

Thank you very much for this bug report.
