### ISSUE TITLE
When 'Telugu' language is selected Search box still shows text in engligh

### ISSUE THREAD

**Issue by ashokgadamsetty** [bugbash/selenium-kiwix#87]
Steps:
1. Select language Telugu
2. Look at the search box.

Issue:
It should show, eqivalent word for search in telugu. But it still shows 'Search', which does not make any sense to customers.

**Comment by kelson42** [comment]
I guess you speak about the Android app. This should be fixed now. Could you please confirm that it works for you with this nightly build?
http://download.kiwix.org/bin/nightly/2014-09-06/kiwix-20140906_cf3b6c40-android.apk

**Comment by kelson42** [comment]
Now fixed. Thank you again for your feedback about this.
