### ISSUE TITLE
Kiwix-Server: Load button for zim file is out of display on Chrome [Linux]

### ISSUE THREAD

**Issue by kapilag** [bugbash/selenium-kiwix#92]
Steps to Reproduce 
1. Start "kiwix-server"
2. Check for top the zim files load button 

More investigation : Tried changing resolution around but still not load button is out of display

**Comment by kapilag** [comment]
![kiwix-server-distortedloadbutton](https://cloud.githubusercontent.com/assets/4065414/4174312/41f583a8-3586-11e4-9c7f-8e972f1dc2aa.jpeg)

**Comment by kelson42** [comment]
Could you please test with http://library.kiwix.org ?
This page uses a cutting edge version of kiwix-serve and to me (with chromium) it works well.

**Comment by kelson42** [comment]
Fixed like we can see on the screenshot.
![screenshot from 2014-09-12 21 16 51](https://cloud.githubusercontent.com/assets/1029718/4255084/8218f2c8-3ab1-11e4-8b2b-45adb06da444.png)

Thank you for this bug report.
