### ISSUE TITLE
Kiwix-Server:Clicking on the Auto-Complete list item doesn't show the Required page

### ISSUE THREAD

**Issue by kapilag** [bugbash/selenium-kiwix#95]
### Steps to Reproduce
1. Run kiwix server
2. load zim file like "Ray Charles"
3. Type "ray" in the Search Bar
4. Click on the auto complete list with name "Ray Charles Anthology"

**_Expected Result**_ :Page with Title "Ray Charles Anthology
**_Actual  Result**_:Search Page with query as "content=wikipedia_en_ray_charles_03_2013&pattern=ray"
### Screen Shot

![kiwix-server-autocomplete](https://cloud.githubusercontent.com/assets/4065414/4174396/8064c356-358b-11e4-8be9-3fd8ccf390a4.jpeg)

**Comment by kelson42** [comment]
This seems to be fixed now. You can check with this cutting edge version:
http://library.kiwix.org/wikipedia_en_ray_charles_03_2013/

**Comment by kelson42** [comment]
Fixed, I close the bug.
