### ISSUE TITLE
(Case sensitive Search)Search list does not auto populate results when search string is mix of both upper case and lower case

### ISSUE THREAD

**Issue by Mohanme13** [bugbash/selenium-kiwix#96]
Zim file is available with Ray Charles content , but when the search is in lowercase string, search auto complete suggestion are not seen.
![screen shot 2014-09-06 at 11 47 47 am](https://cloud.githubusercontent.com/assets/8675914/4174418/9b1523ba-358d-11e4-97cf-666344a7bc73.png)

**Comment by kelson42** [comment]
Yes, this bug is tracked upstream here:
https://sourceforge.net/p/kiwix/feature-requests/186/

Thank you for reporting this.
