### ISSUE TITLE
Hindi Langauage Page

### ISSUE THREAD

**Issue by pavi200863** [bugbash/selenium-kiwix#97]
On hindi Wikipedia  main page ->

click on "पूर्व प्रदर्शित" on any subsection (i.e - निर्वाचित लेख ,समाचार ) 
From “पूर्व प्रदर्शित “  page , now can not click वर्तमान in any subsection ( (i.e - निर्वाचित लेख ,समाचार ) )

**Comment by kelson42** [comment]
Seems to be a duplicate of https://github.com/Bug-Bash/selenium-kiwix/issues/97

**Comment by kelson42** [comment]
I mean https://github.com/Bug-Bash/selenium-kiwix/issues/99
